---
# roles/dnf/tasks/main.yml

## DNF

- name: "Import dnf Tasks"
  ansible.builtin.import_tasks: "dnf.yml"
  tags:
    - "dnf"
    - "configuration"

## DNF automatic

- name: "Import dnf automatic Tasks"
  ansible.builtin.import_tasks: "dnf-automatic.yml"
  when:
    - "dnf_automatic_enabled | bool"
  tags:
    - "dnf"
    - "service"
    - "timer"

## Checks

- name: "Import check Tasks"
  ansible.builtin.import_tasks: "check.yml"
  when:
    - "dnf_checks_enabled | bool"
  tags:
    - "dnf"
    - "check"
...
