---
# roles/chrony/meta/argument_specs.yml

argument_specs:
  # roles/chrony/tasks/main.yml entry point
  main:
    short_description: "The main entrypoint for chrony."
    options:
      chrony_package_names:
        description: "Define the package names."
        type: "list"
        elements: "str"
        default: ["chrony"]
      chrony_package_state:
        description: "Define the package state."
        type: "str"
        choices:
          - "present"
          - "absent"
          - "latest"
        default: "present"
      chrony_service_names:
        description: "Define the service names."
        type: "str"
        default: "chronyd.service"
      chrony_service_state:
        description: "Define the service state."
        type: "str"
        choices:
          - "started"
          - "stopped"
        default: "present"
      chrony_service_enabled:
        description: "Define if the service should be enabled on boot."
        type: "bool"
        default: true
      chrony_checks_enabled:
        description: "Define if checks should run."
        type: "bool"
        default: false
...
