---
# roles/bash/tasks/main.yml

## Include tasks

- name: "Import bash Tasks"
  ansible.builtin.import_tasks: "bash.yml"
  tags:
    - "bash"
    - "package"
    - "development"

- name: "Import powerline Tasks"
  ansible.builtin.import_tasks: "powerline.yml"
  when:
    - "bash_powerline_enabled | bool"
  tags:
    - "bash"
    - "package"
    - "configuration"

- name: "Import starship Tasks"
  ansible.builtin.import_tasks: "starship.yml"
  when:
    - "bash_starship_enabled | bool"
  tags:
    - "bash"
    - "configuration"

- name: "Import dotfiles Tasks"
  ansible.builtin.import_tasks: "dotfiles.yml"
  when:
    - "bash_dotfiles_enabled | bool"
  tags:
    - "bash"
    - "configuration"

## Checks

- name: "Import Checks for bash"
  ansible.builtin.import_tasks: "check.yml"
  when:
    - "bash_checks_enabled | bool"
  tags:
    - "bash"
    - "check"
...
