---
# roles/bash/tasks/main.yml

## Package Management

- name: "Manage bash Packages"
  ansible.builtin.package:
    name: "{{ bash_package_names }}"
    state: "{{ bash_package_state }}"
  become: true
  tags:
    - "bash"
    - "package"

- name: "Manage bash scripting Packages"
  ansible.builtin.package:
    name: "{{ bash_scripting_package_names }}"
    state: "{{ bash_scripting_package_state }}"
  become: true
  tags:
    - "bash"
    - "package"
    - "development"

- name: "Manage bash powerline Packages"
  ansible.builtin.package:
    name: "{{ bash_powerline_package_names }}"
    state: "{{ bash_powerline_package_state }}"
  become: true
  tags:
    - "bash"
    - "powerline"
    - "package"

## Configuration Management

- name: "Manage bash dotfiles Configuration"
  ansible.builtin.template:
    src: "wtd_dotfiles.sh.j2"
    dest: "/etc/profile.d/wtd_dotfiles.sh"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  when:
    - "bash_dotfiles_system_enabled | bool"
  tags:
    - "bash"
    - "dotfiles"
    - "package"

- name: "Manage bash powerline Configuration"
  ansible.builtin.template:
    src: "wtd_powerline.sh.j2"
    dest: "/etc/profile.d/wtd_powerline.sh"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  when:
    - "bash_powerline_system_enabled | bool"
  tags:
    - "bash"
    - "powerline"
    - "package"

## Checks

- name: "Import Checks for bash"
  ansible.builtin.import_tasks: "check.yml"
  when:
    - "bash_checks_enabled | bool"
  tags:
    - "bash"
    - "check"
...
