---
# roles/user/tasks/main.yml

## User Management

- name: "Import user Tasks"
  ansible.builtin.include_tasks: "user.yml"
  loop: "{{ user_users }}"
  loop_control:
    loop_var: "user"
    label: "{{ user.username }}"
  when:
    - "user_users is defined"
    - "user_users | length > 0"
  tags:
    - "user"
    - "sudo"
    - "key"
...
