---
# roles/user/tasks/user.yml

- name: "Manage user Account"
  ansible.builtin.user:
    name: "{{ user.username }}"
    groups: "{{ user.groups | default(omit) }}"
    password: "{{ user.password_hash | default(omit) }}"
    update_password: "{{ user.password_update | default('always') }}"
    uid: "{{ user.uid | default(omit) }}"
    shell: "{{ user.shell | default(omit) }}"
    home: "{{ user.home | default(omit) }}"
    system: "{{ user.system | default(omit) }}"
    state: "{{ user.state | default('present') }}"
  become: true
  tags:
    - "user"

- name: "Manage user sudo Configuration"
  ansible.builtin.template:
    src: "sudoers.d.user.j2"
    dest: "/etc/sudoers.d/user_{{ user.username }}"
    owner: "root"
    group: "root"
    mode: 0400
    validate: "visudo -cf %s"
  become: true
  when:
    - "user.passwordless_sudo | bool"
  tags:
    - "user"
    - "sudo"

- name: "Manage user Authorized Keys"
  ansible.posix.authorized_key:
    user: "{{ user.username }}"
    state: "{{ item.state | default('present') }}"
    key: "{{ item.key }}"
    exclusive: "{{ item.exclusive | default(false) }}"
  become: true
  loop: "{{ user.auth_keys }}"
  when:
    - "user.auth_keys is defined"
    - "user.auth_keys | length > 0"
  tags:
    - "user"
    - "key"
...
