---
# roles/avahi/meta/argument_specs.yml

argument_specs:
  # roles/avahi/tasks/main.yml entry point
  main:
    short_description: "The main entrypoint for avahi."
    options:
      # Package Management
      avahi_package_names:
        description: "Define the package names."
        type: "list"
        elements: "str"
        default: []
      avahi_package_state:
        description: "Define the package state."
        type: "str"
        choices:
          - "present"
          - "absent"
          - "latest"
        default: "present"
      # Service Management
      avahi_service_names:
        description: "Define the service names."
        type: "str"
        default: "avahi-daemon.service"
      avahi_service_state:
        description: "Define the service state."
        type: "str"
        choices:
          - "started"
          - "stopped"
        default: "present"
      avahi_service_enabled:
        description: "Define if the services should be enabled state."
        type: "bool"
        default: "true"
      # Checks
      avahi_checks_enabled:
        description: "Define if checks should run."
        type: "bool"
        default: false
...
