---
# roles/pcp/meta/argument_specs.yml

argument_specs:
  # roles/pcp/tasks/main.yml entry point
  main:
    short_description: "The main entrypoint for pcp."
    options:
      pcp_package_names:
        description: "Define the package names."
        type: "list"
        elements: "str"
        default:
          - "pcp"
      pcp_package_state:
        description: "Define the package state."
        type: "str"
        choices:
          - "present"
          - "absent"
          - "latest"
        default: "present"
      pcp_checks_enabled:
        description: "Define if checks should run.
        type: "bool"
        default: false
...
