---
# roles/cockpit/meta/argument_specs.yml

argument_specs:
  # roles/cockpit/tasks/main.yml entry point
  main:
    short_description: "The main entrypoint for cockpit."
    options:
      cockpit_package_names:
        description: "Define the package names."
        type: "list"
        elements: "str"
        default:
          - "cockpit"
          - "cockpit-networkmanager"
          - "cockpit-storaged"
          - "cockpit-sosreport"
      cockpit_package_state:
        description: "Define the package state."
        type: "str"
        choices:
          - "present"
          - "absent"
          - "latest"
        default: "present"
      cockpit_checks_enabled:
        description: "Define if checks should run.
        type: "bool"
        default: false
...
