---
# roles/k3s/tasks/devel.yml

- name: "Fetch kubeconfig"
  ansible.builtin.fetch:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "/tmp/{{ inventory_hostname }}.kube.config"
    flat: true
  become: true
  tags:
    - "k3s"
    - "devel"

- name: "Adapt kubeconfig"
  ansible.builtin.lineinfile:
    path: /tmp/{{ inventory_hostname }}.kube.config
    regexp: '^    server: https://.*'
    line: '    server: https://{{ ansible_ssh_host }}:6443'
  delegate_to: "localhost"
  tags:
    - "k3s"
    - "devel"
...
