---
# roles/chrony/tasks/check.yml

- name: "Gather package Facts"
  ansible.builtin.package_facts:
    manager: "auto"
  tags:
    - "avahi"
    - "check"

- name: "Check chrony"
  ansible.builtin.assert:
    that:
      - "'chrony' in ansible_facts.packages"
  tags:
    - "avahi"
    - "check"
...
