---
# roles/sudo/tasks/main.yml

## Package Management

- name: "Manage sudo Packages"
  ansible.builtin.package:
    name: "{{ sudo_package_names }}"
    state: "{{ sudo_package_state }}"
  become: true
  notify:
    - "Restart sudo Service"
  tags:
    - "sudo"
    - "package"

## Configuration Management

- name: "Manage sudo Configuration"
  ansible.builtin.template:
    src: "{{ sudo_config_src }}"
    dest: "{{ sudo_config_dest }}"
    owner: "{{ sudo_config_owner }}"
    group: "{{ sudo_config_group }}"
    mode: "{{ sudo_config_mode }}"
  become: true
  notify:
    - "Restart sudo Service"
  tags:
    - "sudo"
    - "configuration"

## Service Management

- name: "Manage sudo Services"
  ansible.builtin.service:
    name: "{{ sudo_service_name }}"
    state: "{{ sudo_service_state }}"
    enabled: "{{ sudo_service_enabled }}"
  become: true
  when:
    - "sudo_package_state != 'absent'"
  tags:
    - "sudo"
    - "package"

## Firewall Management

- name: "Gather package Facts"
  ansible.builtin.package_facts:
    manager: "auto"
  tags:
    - "sudo"
    - "package"

- name: "Manage sudo Firewall Policy"
  ansible.posix.firewalld:
    service: "{{ sudo_firewall_service }}"
    state: "{{ sudo_firewall_state }}"
    zone: "{{ sudo_firewall_zone }}"
    immediate: "{{ sudo_firewall_immediate }}"
    permanent: "{{ sudo_firewall_permanent }}"
  become: true
  when:
    - "'firewalld' in ansible_facts.packages"
  tags:
    - "sudo"
    - "firewall"

## Checks

- name: "Import Checks for sudo"
  ansible.builtin.import_tasks: "check.yml"
  when:
    - "sudo_checks_enabled | bool"
  tags:
    - "sudo"
    - "check"
...
