---
# roles/thermald/meta/argument_specs.yml

argument_specs:
  # roles/thermald/tasks/main.yml entry point
  main:
    short_description: "The main entrypoint for ssh."
    options:

      # Package Management
      thermald_package_names:
        description: "Define the package names."
        type: "list"
        elements: "str"
        default:
          - "thermald"
      thermald_package_state:
        description: "Define the package state."
        type: "str"
        default: "present"
        choices:
          - "present"
          - "absent"
          - "latest"

      # Service Management
      thermald_service_name:
        descrtiption: "The name of the service."
        type: "str"
        default: "thermald.service"
      thermald_service_state:
        description: "The state of the service."
        type: "str"
        default: "started"
        choices:
          - "started"
          - "stopped"
          - "restarted"
      thermald_service_enabled:
        description: "Define if the service should be enabled."
        type: "bool"
        default: true

      # Checks
      thermald_checks_enabled:
        type: "bool"
        default: false
        description: "Define if checks should run."
...
