---
# roles/k3s/defaults/main.yml

## Binary Management

k3s_binary_version: "v1.21.2+k3s1"

## Configuration Management

### k3s type can be initial or server
k3s_type: "initial"
k3s_node_name: "{{ inventory_hostname }}"

k3s_token: ""
k3s_agent_token: ""

## Firewall Management

k3s_api_firewall_port: "6443"
k3s_api_firewall_state: "enabled"
k3s_api_firewall_zone: "public"
k3s_api_firewall_immediate: true
k3s_api_firewall_permanent: true

k3s_etcd_firewall_port: "2379"
k3s_etcd_firewall_state: "enabled"
k3s_etcd_firewall_zone: "public"
k3s_etcd_firewall_immediate: true
k3s_etcd_firewall_permanent: true

## Checks

k3s_check_enabled: false
...
