---
# roles/tuned/tasks/check.yml

- name: "Gather package Facts"
  ansible.builtin.package_facts:
    manager: "auto"
  tags:
    - "tuned"
    - "check"

- name: "Check tuned"
  ansible.builtin.assert:
    that:
      - "'tuned' in ansible_facts.packages"
  tags:
    - "tuned"
    - "check"
...
