---
# playbooks/configure_minimal_server.yml
#
# This playbook provides some minimal automation for servers.
# It can be used as a base-line for further automation.

- name: "Configure Minimal Server"
  hosts: "all"

  tasks:

    - name: "Import bash Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.general.bash"
      tags:
        - "bash"

    - name: "Import chrony Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.general.chrony"
      tags:
        - "chrony"

    - name: "Import dnf Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.general.dnf"
      tags:
        - "dnf"

    - name: "Import firewalld Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.general.firewalld"
      tags:
        - "firewalld"

    - name: "Import misc Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.general.misc"
      tags:
        - "misc"

    - name: "Import selinux Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.general.selinux"
      tags:
        - "selinux"

    - name: "Import sshd Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.general.sshd"
      tags:
        - "ssh"

    - name: "Import sudo Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.general.sudo"
      tags:
        - "ssh"

    - name: "Import user Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.general.user"
      tags:
        - "user"
      vars:
        user_users:
          - username: "admin"
            groups:
              - "wheel"
            # password: password
            # yamllint disable-line rule:line-length
            password_hash: "$6$x.qGDTCdeViBtCwb$NNpBlMcpglRnJJSBU6TduvcqS4xTeKEsw5l41IZ519Nh62.0rDo4NXf.dHAI89.QnMW6I.pIn0LBjAVEOrTsM0"
            passwordless_sudo: true
            state: "present"
...
