---
# playbooks/minimal.yml for whiletruedoio.general
#
# This playbook provides some minimal automation for servers and desktops.
# It can be used as a base-line for further automations.

- name: "Minimal Server"
  hosts: "all"

  tasks:

    - name: "Import misc Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.general.misc"

    - name: "Import dnf Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.general.dnf"

    - name: "Import chrony Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.general.chrony"

    - name: "Import bash Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.general.bash"

    - name: "Import selinux Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.general.selinux"

    - name: "Import firewalld Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.general.firewalld"

    - name: "Import ssh Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.general.ssh"

    - name: "Import user Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.general.user"
      vars:
        user_users:
          - username: "admin"
            groups:
              - "wheel"
            # password: password
            password_hash: "$6$x.qGDTCdeViBtCwb$NNpBlMcpglRnJJSBU6TduvcqS4xTeKEsw5l41IZ519Nh62.0rDo4NXf.dHAI89.QnMW6I.pIn0LBjAVEOrTsM0"
            passwordless_sudo: true
            state: "present"
...
