---
# playbooks/updates.yml

- name: "Update Machines"
  hosts: "all"

  tasks:

    - name: "Import update Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.general.update"
      tags:
        - "update"
...
