---
# roles/misc/tasks/machine_id.yml

## Configuration Management

- name: "Manage machine-id Configuration"
  ansible.builtin.command:
    cmd: "systemd-machine-id-setup"
  become: true
  changed_when: false
  tags:
    - "misc"
    - "machine_id"
    - "configuration"
...
