---
# roles/podman/handlers/main.yml

- name: "Restart podman Service"
  ansible.builtin.service:
    name: "{{ podman_service_name }}"
    state: "restarted"
  become: true
  when:
    - "podman_package_state != 'absent'"
  tags:
    - "podman"
    - "package"
    - "configuration"
    - "service"
...